#!/bin/bash
# Machine installation script for Game Task Emulator
# This script sets up the systemd service and timer for daily execution

set -e

# Configuration
INSTALL_DIR="/opt/gameTaskEmulator"
SERVICE_NAME="gametask-emulator"
SYSTEMD_DIR="/etc/systemd/system"
ENV_FILE="/etc/default/${SERVICE_NAME}"
CURRENT_USER="${SUDO_USER:-${USER}}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

log_step() {
    echo -e "${BLUE}[STEP]${NC} $1"
}

# Show usage
usage() {
    cat << EOF
Usage: $0 [OPTIONS]

Install Game Task Emulator as a systemd service with daily timer.

OPTIONS:
    -t, --team TEAM_CODE    Team city code (e.g., DAL, CHI, BOS)
                           Can specify multiple teams: -t DAL,CHI,BOS
                           Default: no team (Dallas Stars)

    -f, --flags FLAGS      Additional flags to pass to the application
                           Default: -today
                           Example: -f "-today -prod"

    -u, --user USER        User to run the service as
                           Default: current user (${CURRENT_USER})

    -h, --help            Show this help message

EXAMPLES:
    # Install with default settings (Dallas Stars, -today flag)
    sudo $0

    # Install for Chicago Blackhawks
    sudo $0 --team CHI

    # Install for multiple teams
    sudo $0 --team CHI,DAL,BOS

    # Install with production flag
    sudo $0 --team DAL --flags "-today -prod"

    # Install as specific user
    sudo $0 --user myuser --team CHI

EOF
    exit 1
}

# Check if running as root
check_root() {
    if [ "$EUID" -ne 0 ]; then
        log_error "This script must be run as root (use sudo)"
        exit 1
    fi
}

# Check dependencies
check_dependencies() {
    log_step "Checking dependencies..."

    local missing_deps=()

    if ! command -v docker &> /dev/null; then
        missing_deps+=("docker")
    fi

    if ! command -v git &> /dev/null; then
        missing_deps+=("git")
    fi

    if ! command -v systemctl &> /dev/null; then
        missing_deps+=("systemd")
    fi

    if [ ${#missing_deps[@]} -ne 0 ]; then
        log_error "Missing required dependencies: ${missing_deps[*]}"
        log_error "Please install the missing dependencies and try again"
        exit 1
    fi

    log_info "All dependencies are installed"
}

# Parse command line arguments
TEAM_CODE=""
ADDITIONAL_FLAGS="-today"
RUN_AS_USER="${CURRENT_USER}"

while [[ $# -gt 0 ]]; do
    case $1 in
        -t|--team)
            TEAM_CODE="$2"
            shift 2
            ;;
        -f|--flags)
            ADDITIONAL_FLAGS="$2"
            shift 2
            ;;
        -u|--user)
            RUN_AS_USER="$2"
            shift 2
            ;;
        -h|--help)
            usage
            ;;
        *)
            log_error "Unknown option: $1"
            usage
            ;;
    esac
done

# Main installation
main() {
    check_root
    check_dependencies

    log_info "Installing Game Task Emulator"
    log_info "Team Code: ${TEAM_CODE:-none (default: Dallas Stars)}"
    log_info "Additional Flags: ${ADDITIONAL_FLAGS}"
    log_info "Run as User: ${RUN_AS_USER}"
    echo

    # Verify user exists
    if ! id "${RUN_AS_USER}" &>/dev/null; then
        log_error "User '${RUN_AS_USER}' does not exist"
        exit 1
    fi

    # Create installation directory
    log_step "Creating installation directory: ${INSTALL_DIR}"
    mkdir -p "${INSTALL_DIR}"

    # Copy repository files to installation directory
    log_step "Copying repository files..."
    SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

    # Copy necessary files
    cp "${SCRIPT_DIR}/run.sh" "${INSTALL_DIR}/"
    chmod +x "${INSTALL_DIR}/run.sh"

    # Set ownership
    chown -R "${RUN_AS_USER}:${RUN_AS_USER}" "${INSTALL_DIR}"

    log_info "Files copied to ${INSTALL_DIR}"

    # Create environment configuration file
    log_step "Creating environment configuration..."
    cat > "${ENV_FILE}" << EOF
# Environment configuration for Game Task Emulator
# Generated by install script on $(date)

# Team city code
TEAM_CODE=${TEAM_CODE}

# Additional flags
ADDITIONAL_FLAGS=${ADDITIONAL_FLAGS}

# User running the service
SERVICE_USER=${RUN_AS_USER}
EOF

    chmod 644 "${ENV_FILE}"
    log_info "Environment configuration created at ${ENV_FILE}"

    # Install systemd service file
    log_step "Installing systemd service..."

    # Create a modified service file with the correct user
    cat > "${SYSTEMD_DIR}/${SERVICE_NAME}.service" << EOF
[Unit]
Description=Game Task Emulator - NHL Game Tracker Scheduler
Documentation=https://github.com/FirepowerApp/gameTaskEmulator
After=network-online.target docker.service
Wants=network-online.target
Requires=docker.service

[Service]
Type=oneshot
User=${RUN_AS_USER}
WorkingDirectory=${INSTALL_DIR}

# Environment file for configuration
EnvironmentFile=-${ENV_FILE}

# Set default values if not specified in environment file
Environment="TEAM_CODE="
Environment="ADDITIONAL_FLAGS=-today"

# Execute the run script with team code if specified
ExecStart=/bin/bash -c '${INSTALL_DIR}/run.sh \${ADDITIONAL_FLAGS} \${TEAM_CODE:+-teams} \${TEAM_CODE}'

# Logging
StandardOutput=journal
StandardError=journal
SyslogIdentifier=${SERVICE_NAME}

# Security settings
NoNewPrivileges=true
PrivateTmp=true

# Restart policy
Restart=on-failure
RestartSec=5s

[Install]
WantedBy=multi-user.target
EOF

    log_info "Service file installed"

    # Install systemd timer file
    log_step "Installing systemd timer..."
    cp "${SCRIPT_DIR}/systemd/${SERVICE_NAME}.timer" "${SYSTEMD_DIR}/"

    log_info "Timer file installed"

    # Reload systemd
    log_step "Reloading systemd daemon..."
    systemctl daemon-reload

    # Enable and start the timer
    log_step "Enabling and starting timer..."
    systemctl enable "${SERVICE_NAME}.timer"
    systemctl start "${SERVICE_NAME}.timer"

    # Show status
    echo
    log_info "Installation complete!"
    echo
    log_info "Service Status:"
    systemctl status "${SERVICE_NAME}.timer" --no-pager || true
    echo
    log_info "Next scheduled run:"
    systemctl list-timers "${SERVICE_NAME}.timer" --no-pager || true
    echo
    log_info "Useful commands:"
    echo "  View timer status:        systemctl status ${SERVICE_NAME}.timer"
    echo "  View service status:      systemctl status ${SERVICE_NAME}.service"
    echo "  View logs:                journalctl -u ${SERVICE_NAME}.service -f"
    echo "  Run manually now:         systemctl start ${SERVICE_NAME}.service"
    echo "  Edit configuration:       sudo nano ${ENV_FILE}"
    echo "  Restart timer:            systemctl restart ${SERVICE_NAME}.timer"
    echo "  Disable timer:            systemctl disable ${SERVICE_NAME}.timer"
    echo
}

# Run main installation
main
